image: jelle/singularity-docker:gitlab-3.1-slim

build:
  before_script:
    # Configure the SYLABS_TOKEN as CI Environment Variable in Gitlab
    - echo $SYLABS_TOKEN > $TOKENFILE
  script:
    # step 1. build the container!
    - /bin/bash .gitlabci/build.sh Singularity
    # step 2. push to library
    - singularity -t $TOKENFILE push Singularity.sif library://$USER/$PROJECT/$CONTAINER:$TAG
    # step 3. build artifacts, although git.embl.de restrict the size, so not that useful atm. 
    # - mkdir -p build && cp *.sif build
    # - mkdir -p build && cp Singularity* build

  # This is where you can save job artifacts
  # https://docs.gitlab.com/ee/user/project/pipelines/job_artifacts.html
  # You can specify the path to containers or the build folder to save.
  # Don't forget to save your recipes too!
  #artifacts:
  #    paths:
  #      - build/Singularity.sif
  #      - build/Singularity

variables:
  # Variables that will be used in the build commands
  USER: "scholtalbers"
  PROJECT: "default"
  CONTAINER: "gifascii"
  TAG: "latest"
  TOKENFILE: "sylabs-token"
